### ISSUE TITLE
예매공지 및 관람공지

### ISSUE THREAD

**Issue by JuneBuug** [WTMKorea/WTMKorea18#4]
## 예매 공지 
* 인원이 한정되어있어 조기에 마감 될 수 있습니다.
* 사전 구매하신 분에게 따로 티켓이 배송되지 않으며, 현장에서 신청 확인 후 입장 안내 드립니다.
* 환불은 행사 10일 전인 3월 28일 까지 가능합니다.
환불을 원하실 경우, womentechmakersko@gmail.com 로 성함과 연락처를 보내주시기 바랍니다.
* 양도는 행사 전날인 4월 6일 까지 가능합니다.
양도를 원하실 경우, womentechmakersko@gmail.com 로 양도 하시는 분의 성함, 연락처와 양도 받는 분의 성함과 연락처를 보내주시길 바랍니다. 

## 관람공지 
* 컨퍼런스 참석 진행 및 입장은 당일 오전 11시 반 부터 가능합니다.
* 강연 중간 입장은 가능합니다, 다만 세션 연출이나 안전 상의 문제로 잠시 출입이 불가능할 수 있으니 스태프의 안내에 따라주시기 바랍니다. 
* 주차 지원은 되지 않으니, 대중교통 이용 부탁드립니다.
* WTM은 세션장에 아이와 함께 들을 수 있는 자리를 마련했습니다. 
  아이들이 있으니 세션장 내에서는 조심해서 이동해주세요.
* 장내에서 타인에게 피해를 주지 않도록 무음으로 촬영해주시길 바랍니다.

**Comment by nameisys** [comment]
관람공지에 추가해주세욥

- 주차 지원은 불가하오니 , 대중교통 이용을 부탁드립니다.

- Wi-Fi와 노트북 충전을 위한 콘센트는 코드랩 진행시에만 사용 가능합니다.
